# Generated by Django 2.0.3 on 2018-04-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar_picture_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
