# Generated by Django 2.0.3 on 2018-04-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptocoins', '0002_auto_20180409_1518'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_coins',
            field=models.ManyToManyField(to='cryptocoins.Cryptocurrency'),
        ),
    ]
